/*
 * API Nuvem Fiscal
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = NuvemFiscal.Sdk.Client.FileParameter;
using OpenAPIDateConverter = NuvemFiscal.Sdk.Client.OpenAPIDateConverter;

namespace NuvemFiscal.Sdk.Model
{
    /// <summary>
    /// NfseCancelamento
    /// </summary>
    [DataContract(Name = "NfseCancelamento")]
    public partial class NfseCancelamento : IEquatable<NfseCancelamento>, IValidatableObject
    {
        /// <summary>
        /// Defines status
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum StatusEnum
        {
            /// <summary>
            /// Enum Pendente for value: pendente
            /// </summary>
            [EnumMember(Value = "pendente")]
            Pendente = 1,

            /// <summary>
            /// Enum FilaCancelamento for value: fila_cancelamento
            /// </summary>
            [EnumMember(Value = "fila_cancelamento")]
            FilaCancelamento = 2,

            /// <summary>
            /// Enum Concluido for value: concluido
            /// </summary>
            [EnumMember(Value = "concluido")]
            Concluido = 3,

            /// <summary>
            /// Enum Rejeitado for value: rejeitado
            /// </summary>
            [EnumMember(Value = "rejeitado")]
            Rejeitado = 4

        }


        /// <summary>
        /// Gets or Sets status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public StatusEnum? status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="NfseCancelamento" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="status">status.</param>
        /// <param name="dataHora">dataHora.</param>
        /// <param name="mensagens">mensagens.</param>
        public NfseCancelamento(string id = default(string), StatusEnum? status = default(StatusEnum?), DateTime dataHora = default(DateTime), List<NfseMensagemRetorno> mensagens = default(List<NfseMensagemRetorno>))
        {
            this.id = id;
            this.status = status;
            this.data_hora = dataHora;
            this.mensagens = mensagens;
        }

        /// <summary>
        /// Gets or Sets id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string id { get; set; }

        /// <summary>
        /// Gets or Sets data_hora
        /// </summary>
        [DataMember(Name = "data_hora", EmitDefaultValue = false)]
        public DateTime data_hora { get; set; }

        /// <summary>
        /// Gets or Sets mensagens
        /// </summary>
        [DataMember(Name = "mensagens", EmitDefaultValue = false)]
        public List<NfseMensagemRetorno> mensagens { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NfseCancelamento {\n");
            sb.Append("  id: ").Append(id).Append("\n");
            sb.Append("  status: ").Append(status).Append("\n");
            sb.Append("  data_hora: ").Append(data_hora).Append("\n");
            sb.Append("  mensagens: ").Append(mensagens).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NfseCancelamento);
        }

        /// <summary>
        /// Returns true if NfseCancelamento instances are equal
        /// </summary>
        /// <param name="input">Instance of NfseCancelamento to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NfseCancelamento input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.id == input.id ||
                    (this.id != null &&
                    this.id.Equals(input.id))
                ) && 
                (
                    this.status == input.status ||
                    this.status.Equals(input.status)
                ) && 
                (
                    this.data_hora == input.data_hora ||
                    (this.data_hora != null &&
                    this.data_hora.Equals(input.data_hora))
                ) && 
                (
                    this.mensagens == input.mensagens ||
                    this.mensagens != null &&
                    input.mensagens != null &&
                    this.mensagens.SequenceEqual(input.mensagens)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.id != null)
                {
                    hashCode = (hashCode * 59) + this.id.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.status.GetHashCode();
                if (this.data_hora != null)
                {
                    hashCode = (hashCode * 59) + this.data_hora.GetHashCode();
                }
                if (this.mensagens != null)
                {
                    hashCode = (hashCode * 59) + this.mensagens.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
